### ISSUE TITLE
Improve shutdown process when no Trezor is attached

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hardware#13]
At present an exception is generated if no Trezor is attached in `AbstractHardwareWalletState` due to the event message not being present.

**Comment by gary-rowe** [comment]
Ready for review and close. To verify perform a hard shutdown without a Trezor and observe no exception from MultiBit Hardware.

**Comment by jim618** [comment]
Rebuilt multibit-hardware and MBHD. Open and close without Trezor attached. No exception in log.

Closing.
