### ISSUE TITLE
Support Trezor 1.3.3 (breaking change)

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hardware#15]
There is a breaking change in Trezor 1.3.3 firmware - GetPublicKey now issues a PIN challenge

**Comment by slush0** [comment]
Hi Jim, PIN challenges are hardcoded to workflows? If they're implemented
properly - as event handlers for PinMatrixRequest, no change in client
codebase is required.

Best,
Marek

**Comment by gary-rowe** [comment]
We use event handlers, we just don't expect all events in all workflows. 

This translates up the stack into MBHD where wizard screens progress based on expected events rather than randomly skip around due to unexpected messages being pushed from the device.

**Comment by slush0** [comment]
I see. However, it should be pretty straightforward to change event handler to expect PIN and/or passphrase (well, you don't support passphrases yet, but the logic is the same) messages for virtually any message.

Also, Trezor uses caching mechanism for PIN and passphrase, so not every "PIN protected" message will trigger PinRequest on every call.

**Comment by gary-rowe** [comment]
Yes, it's a breaking change for us but not a difficult one. The [ConfirmGetPublicKey](https://github.com/bitcoin-solutions/multibit-hardware/blob/develop/core/src/main/java/org/multibit/hd/hardware/core/fsm/ConfirmGetPublicKeyState.java) simply needs support for PIN added. 

This then bubbles up to MBHD to trigger the PIN handling in the FSM backing the credentials wizard.

**Comment by jim618** [comment]
As Gary states, it's not a big issue.
There will most likely be a gap in time from when Trezor 1.3.3 comes out and when we release MBHD Beta 8 (as we have other stuff to get in) but it should not be problematic.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
