### ISSUE TITLE
Add support for Ping

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hardware#18]
The `HidService` does not directly support a requestPing() which is an API omission.

**Comment by gary-rowe** [comment]
This should have the side-effect of providing a correctly wrapped message for an external 'ClearSession' message from myTREZOR.com. See [MultiBit HD #603](https://github.com/bitcoin-solutions/multibit-hd/issues/603).

Ready for review and close.

**Comment by jim618** [comment]
Code reviewed - looks ok.
Closing.
