### ISSUE TITLE
Getting `Device not attached` error

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hardware#20]
The following was received from [user BakSAj on Bitcoin Talk](https://bitcointalk.org/index.php?action=post;topic=1331390.0):

Hi, 

I'm struggling with MB HW API for Trezor device. I'm using examples from the repo below, but I always get `TrezorV1HidHardwareWallet - Device not attached.` 

One idea is that project was not tested with latest Trezor firmware. 

I've tried Java7 32, Java7 64, Java8 64. Any ideas? Thank You.
```
Log fragment after running TrezorV1FeaturesExample.main():
16:10:24.821 [default] [safe-scheduled-monitor-hw-client-0] DEBUG o.m.h.h.t.c.TrezorHardwareWalletClient - Attempting to connect...
16:10:24.821 [default] [safe-scheduled-monitor-hw-client-0] DEBUG o.m.h.h.t.w.v.TrezorV1HidHardwareWallet - Suspect recently detached device. Attempting to locate...
16:10:24.830 [default] [safe-scheduled-monitor-hw-client-0] INFO  o.m.h.h.t.w.v.TrezorV1HidHardwareWallet - Device not attached
16:10:24.831 [default] [safe-scheduled-monitor-hw-client-0] DEBUG o.m.h.h.t.w.v.TrezorV1HidHardwareWallet - Failed to locate. Device must be detached. 
```

**Comment by gary-rowe** [comment]
As new Trezor/KeepKey firmware is released the MultiBit Hardware project is verified against it and any updates made as required.

A `Device not attached` message is not firmware dependent - that would show up as a firmware incompatibility message after a `DEVICE_CONNECTED` message was received. 

What you're seeing here is a successful device locate through the HID API followed by an attempt to `connect()` which then discovers that the device has not been located after all. There should be a lot more logging going on in the Example module so you may want to verify that `src/main/resources/logback.xml` is present on your classpath when running `TrezorV1FeaturesExample`.

One thing that may be causing the problem is if another application is also attempting to talk to the Trezor device. Perhaps you have a browser window open to the mytrezor.com website - or another application running in the background, such as MultiBit HD.

**Comment by lizner** [comment]
Problem solved! Thank You. I had to close MyTrezor web application (with Chrome extension).

Im wondering if this could be somewhat enhanced that two clients can use trezor..?

HardwareMessage:
org.multibit.hd.hardware.core.messages.Features@c4e207b[
  vendor=bitcointrezor.com
  version=1.3.4
....

**Comment by gary-rowe** [comment]
No worries. There is a note in the README about this kind of thing but it's easily missed. 

Regarding sharing a single Trezor with multiple clients, I'd advise against it. The single state machine in the Trezor can get confused if two clients are attempting to work through two separate use cases which is why it's best to keep them exclusive. It could be solved by using the session parameter to keep everything separated, but I've not looked into it and I find that keeping it simple works best.

Given that the issue is solved, I'll close it now. 

Remember to work through all the examples and the wallet so you get a good feel for the API.

**Comment by gary-rowe** [comment]
Just added the note (I thought it was there but it wasn't).
